reporting-disabled = true

[meta]
  dir = "/var/lib/influxdb/meta"
  logging-enabled = false

[data]
  dir = "/var/lib/influxdb/data"
  engine = "tsm1"
  wal-dir = "/var/lib/influxdb/wal"
  query-log-enabled = true
  trace-logging-enabled = false

  cache-max-memory-size = "1350000000"
  cache-snapshot-memory-size = "25000000"
  cache-snapshot-write-cooldown = "10s"

  max-select-point = 100000
  max-select-series = 10000
  max-select-buckets = 1000

  max-values-per-tag = 100000
  max-series-per-database = 1000000
  shard-group-duration = "1w"

  max-compaction-threads = 4

[monitor]
  # Whether to record statistics internally.
  store-enabled = false
  store-database = "_internal"
  store-interval = "10s"

[logging]
  format = "auto"
  level = "info"

[retention]
  enabled = true
  check-interval = "30m"

[shard-precreation]
  enabled = true
  check-interval = "30m"
  advance-period = "48h"

[http]
  log-enabled = false
  pprof-enabled = false
  idle-timeout = "30s"
  query-timeout = "1m"

  max-row-limit = 10000
  max-concurrent-queries = 100
  max-requests-per-second = 100
  max-body-size = 25000000
  max-enqueued-write-limit = 10000

[[udp]]
  # Default UDP for Telegraf
  enabled = true
  bind-address = ":9096" # the bind address
  database = "telegraf" # Name of the database that will be written to
  batch-size = 5000 # will flush if this many points get buffered
  batch-timeout = "1s" # will flush at least this often even if the batch-size is not reached
  batch-pending = 10 # number of batches that may be pending in memory
  read-buffer = 0 # UDP read buffer size, 0 means to use OS default
